/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MarginlyPool } from "./MarginlyPool";
export * as factories from "./factories";
export { MarginlyPool__factory } from "./factories/MarginlyPool__factory";
